# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = ".air"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./.air/main ./cmd/api/dev/main.go"
# Binary file yields from `cmd`.
bin = ".air/main"
# Customize binary, can setup environment variables when run your app.
full_bin = "./.air/main"
# Watch these filename extensions.
include_ext = ["go", "gql", "html"]
# Watch these directories if you specified.
include_dir = [
  "api",
  "cmd",
  "ent/entc",
  "ent/entc.go",
  "ent/hook",
  "ent/schema",
  "gql",
  "pkg",
  "resolver",
]
# Ignore these filename extensions or directories.
exclude_dir = []
# Watch these files.
include_file = ["ent/entc.go"]
# Exclude files.
exclude_file = ["ent/hook/hook.go"]
# Exclude specific regular expressions.
exclude_regex = ["_test\\.go"]
# Exclude unchanged files.
exclude_unchanged = true
# Follow symlink for directories
follow_symlink = true
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 800 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Delay after sending Interrupt signal
kill_delay = 800 # ms
# Add additional arguments when running binary (bin/full_bin). Will run './tmp/main hello world'.
args_bin = []

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete .air directory on exit
clean_on_exit = false
