steps:
  # Build the container image
  - id: api:build
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--file', '${_DOCKER_FILE}',
      '--target', '${_DOCKER_STAGE_NAME}',
      '-t', '${_IMAGE}', '.'
    ]

  # Push the container image to Container Registry
  - id: api:push
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  # Deploy container image to Cloud Run
  - id: api:deploy
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run','deploy', '${_PROJECT_NAME}',
      '--project', '${_PROJECT_ID}',
      '--region', '${_REGION}',
      '--image', '${_IMAGE}',
      '--add-cloudsql-instances', '${_SQL_INSTANCE}',
      '--set-env-vars', '"DATABASE_URL=${_SQL_URL}"',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - ${_IMAGE}
