version: "3.8"

services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:14
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: -p ${DB_PORT}
    volumes:
      - ./.docker/${DB_CONTAINER_NAME}:/var/lib/postgresql/data

  db-gui:
    container_name: ${DB_GUI_CONTAINER_NAME}
    image: sosedoff/pgweb:latest
    ports:
      - "${DB_GUI_PORT}:${DB_GUI_PORT}"
    environment: 
      DATABASE_URL: ${DB_URL}
    depends_on:
      - db
    volumes:
      - ./.docker/${DB_GUI_CONTAINER_NAME}:/var/lib/postgresql/data

  api:
    container_name: ${API_CONTAINER_NAME}
    build:
      dockerfile: Dockerfile.api
      target: dev
    ports:
      - "${API_PORT}:${API_PORT}"
    expose:
      - ${API_PORT}
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/.credential.json
    depends_on:
      - db
    volumes:
      -  .:/app

  api-production-test:
    build:
      dockerfile: Dockerfile.api
      target: runner
      no_cache: true
    ports:
      - "${GCP_API_PORT}:${GCP_API_PORT}"
    profiles:
      - test

  migration-production-test:
    build:
      dockerfile: Dockerfile.sql
      target: migration
    environment:
      URL: ${DB_CONNECTION_URL}
    profiles:
      - test
