version: "3.8"

services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:14
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: -p ${DB_PORT}

  db-gui:
    container_name: ${DB_GUI_CONTAINER_NAME}
    image: sosedoff/pgweb:latest
    ports:
      - "${DB_GUI_PORT}:${DB_GUI_PORT}"
    environment: 
      DATABASE_URL: ${DB_URL}
    depends_on:
      - db
  
  migrate-db:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: migrate-db
      no_cache: true
    volumes:
      - .:/app
    depends_on:
      - db

  api:
    container_name: ${API_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-api
    ports:
      - "${API_PORT}:${API_PORT}"
    expose:
      - ${API_PORT}
    volumes:
      - .:/app
    depends_on:
      - db
