// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app/ent/newstagging"
	"app/ent/predicate"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// NewsTaggingDelete is the builder for deleting a NewsTagging entity.
type NewsTaggingDelete struct {
	config
	hooks    []Hook
	mutation *NewsTaggingMutation
}

// Where appends a list predicates to the NewsTaggingDelete builder.
func (ntd *NewsTaggingDelete) Where(ps ...predicate.NewsTagging) *NewsTaggingDelete {
	ntd.mutation.Where(ps...)
	return ntd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ntd *NewsTaggingDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ntd.hooks) == 0 {
		affected, err = ntd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NewsTaggingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ntd.mutation = mutation
			affected, err = ntd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ntd.hooks) - 1; i >= 0; i-- {
			if ntd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ntd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ntd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ntd *NewsTaggingDelete) ExecX(ctx context.Context) int {
	n, err := ntd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ntd *NewsTaggingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: newstagging.Table,
		},
	}
	if ps := ntd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ntd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// NewsTaggingDeleteOne is the builder for deleting a single NewsTagging entity.
type NewsTaggingDeleteOne struct {
	ntd *NewsTaggingDelete
}

// Exec executes the deletion query.
func (ntdo *NewsTaggingDeleteOne) Exec(ctx context.Context) error {
	n, err := ntdo.ntd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{newstagging.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ntdo *NewsTaggingDeleteOne) ExecX(ctx context.Context) {
	ntdo.ntd.ExecX(ctx)
}
