// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// News is the predicate function for news builders.
type News func(*sql.Selector)

// NewsTagging is the predicate function for newstagging builders.
type NewsTagging func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
